export const offers = [
  {
    id: 1,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
    isPremium: false,
    isFavorite: false,
    price: 493,
    title: `The house among olive `,
    guests: 4,
    bedrooms: 3,
    description: `Discover daily local life in city center, friendly neighborhood, clandestine casino,
    karaoke, old-style artisans, art gallery and artist studio downstairs.`,
    facilities: [
      `Laptop friendly workspace`,
      `Washer`,
      `Towels`,
      `Fridge`,
      `Air conditioning`,
      `Baby seat`,
      `Breakfast`,
    ],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [50.957361, 6.9509739999999995],
    locationZoom: 16,
    cityName: `Cologne`,
    cityCoordinates: [50.938361, 6.959974],
    cityZoom: 13,
    type: `house`,
    rating: 3.8,
  },
  {
    id: 2,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
    isPremium: false,
    isFavorite: false,
    price: 323,
    title: `Amazing and Extremely Central Flat`,
    guests: 8,
    bedrooms: 3,
    description: `This is a place for dreamers to reset, reflect, and create.
     Designed with a 'slow' pace in mind, our hope is that you enjoy every part of your stay; from making local coffee by drip in the morning,
      choosing the perfect record to put on as the sun sets.`,
    facilities: [
      `Towels`,
      `Baby seat`,
      `Laptop friendly workspace`,
      `Dishwasher`,
      `Washing machine`,
      `Air conditioning`,
      `Washer`,
      `Coffee machine`,
      `Breakfast`,
      `Fridge`,
    ],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [50.839557, 4.346697],
    locationZoom: 16,
    cityName: `Brussels`,
    cityCoordinates: [50.846557, 4.351697],
    cityZoom: 13,
    type: `apartment`,
    rating: 4.3,
  },
  {
    id: 3,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
    isPremium: false,
    isFavorite: false,
    price: 218,
    title: `The house among olive `,
    guests: 7,
    bedrooms: 4,
    description: `Relax, rejuvenate and unplug in this ultimate rustic getaway experience in the country.
     In our beautiful screened Pondhouse, you can gaze at the stars and listen to the sounds of nature from your cozy warm bed.`,
    facilities: [
      `Washer`,
      `Laptop friendly workspace`,
      `Breakfast`,
      `Air conditioning`,
      `Baby seat`,
    ],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [50.865556999999995, 4.371696999999999],
    locationZoom: 16,
    cityName: `Brussels`,
    cityCoordinates: [50.846557, 4.351697],
    cityZoom: 13,
    type: `apartment`,
    rating: 4.6,
  },
  {
    id: 4,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
    isPremium: false,
    isFavorite: false,
    price: 440,
    title: `Perfectly located Castro`,
    guests: 7,
    bedrooms: 3,
    description: `Relax, rejuvenate and unplug in this ultimate rustic getaway experience in the country.
     In our beautiful screened Pondhouse, you can gaze at the stars and listen to the sounds of nature from your cozy warm bed.`,
    facilities: [
      `Dishwasher`,
      `Air conditioning`,
      `Laptop friendly workspace`,
      `Washer`,
      `Baby seat`,
      `Towels`,
      `Breakfast`,
      `Coffee machine`,
      `Fridge`,
    ],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [52.385540000000006, 4.902976],
    locationZoom: 16,
    cityName: `Amsterdam`,
    cityCoordinates: [52.37454, 4.897976],
    cityZoom: 13,
    type: `house`,
    rating: 4.6,
  },
  {
    id: 5,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
    isPremium: false,
    isFavorite: false,
    price: 134,
    title: `The house among olive `,
    guests: 3,
    bedrooms: 1,
    description: `A new spacious villa, one floor. All commodities, jacuzzi and beautiful scenery. Ideal for families or friends.`,
    facilities: [`Laptop friendly workspace`, `Washer`, `Breakfast`],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [52.388540000000006, 4.899976],
    locationZoom: 16,
    cityName: `Amsterdam`,
    cityCoordinates: [52.37454, 4.897976],
    cityZoom: 13,
    type: `room`,
    rating: 2.2,
  },
  {
    id: 6,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
    isPremium: false,
    isFavorite: false,
    price: 226,
    title: `The house among olive `,
    guests: 8,
    bedrooms: 5,
    description: `Peaceful studio in the most wanted area in town. Quiet house Near of everything.
     Completely renovated. Lovely neighbourhood, lot of trendy shops, restaurants and bars in a walking distance.`,
    facilities: [
      `Dishwasher`,
      `Fridge`,
      `Towels`,
      `Washer`,
      `Breakfast`,
      `Baby seat`,
      `Laptop friendly workspace`,
      `Air conditioning`,
      `Coffee machine`,
    ],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [48.877610000000004, 2.333499],
    locationZoom: 16,
    cityName: `Paris`,
    cityCoordinates: [48.85661, 2.351499],
    cityZoom: 13,
    type: `apartment`,
    rating: 3,
  },
  {
    id: 7,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
    isPremium: false,
    isFavorite: false,
    price: 277,
    title: `Loft Studio in the Central Area`,
    guests: 3,
    bedrooms: 2,
    description: `Relax, rejuvenate and unplug in this ultimate rustic getaway experience in the country.
    In our beautiful screened Pondhouse, you can gaze at the stars and listen to the sounds of nature from your cozy warm bed.`,
    facilities: [
      `Washer`,
      `Fridge`,
      `Air conditioning`,
      `Baby seat`,
      `Breakfast`,
      `Towels`,
      `Laptop friendly workspace`,
    ],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [53.538341, 9.976654000000002],
    locationZoom: 16,
    cityName: `Hamburg`,
    cityCoordinates: [53.550341, 10.000654],
    cityZoom: 13,
    type: `hotel`,
    rating: 2.3,
  },
  {
    id: 8,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
    isPremium: false,
    isFavorite: false,
    price: 129,
    title: `Amazing and Extremely Central Flat`,
    guests: 1,
    bedrooms: 1,
    description: `Discover daily local life in city center, friendly neighborhood, clandestine casino, karaoke, old-style artisans, art gallery and artist studio downstairs.`,
    facilities: [
      `Baby seat`,
      `Fridge`,
      `Towels`,
      `Air conditioning`,
      `Breakfast`,
      `Washer`,
      `Laptop friendly workspace`,
    ],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [51.204402, 6.7773140000000005],
    locationZoom: 16,
    cityName: `Dusseldorf`,
    cityCoordinates: [51.225402, 6.776314],
    cityZoom: 13,
    type: `room`,
    rating: 2.3,
  },
  {
    id: 9,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
    isPremium: false,
    isFavorite: false,
    price: 308,
    title: `Canal View Prinsengracht`,
    guests: 9,
    bedrooms: 3,
    description: `Relax, rejuvenate and unplug in this ultimate rustic getaway experience in the country. In our beautiful screened Pondhouse, you can gaze at the stars and listen to the sounds of nature from your cozy warm bed.`,
    facilities: [
      `Towels`,
      `Laptop friendly workspace`,
      `Washer`,
      `Baby seat`,
      `Breakfast`,
      `Air conditioning`,
    ],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [50.930361, 6.937974],
    locationZoom: 16,
    cityName: `Cologne`,
    cityCoordinates: [50.938361, 6.959974],
    cityZoom: 13,
    type: `hotel`,
    rating: 4.9,
  },
  {
    id: 10,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
    isPremium: false,
    isFavorite: false,
    price: 125,
    title: `Penthouse, 4-5 rooms + 5 balconies`,
    guests: 2,
    bedrooms: 1,
    description: `Design interior in most sympathetic area! Complitely renovated, well-equipped, cosy studio in idyllic,
    over 100 years old wooden house. Calm street, fast connection to center and airport.`,
    facilities: [
      `Breakfast`,
      `Laptop friendly workspace`,
      `Air conditioning`,
      `Washer`,
    ],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [51.211402, 6.756314000000001],
    locationZoom: 16,
    cityName: `Dusseldorf`,
    cityCoordinates: [51.225402, 6.776314],
    cityZoom: 13,
    type: `apartment`,
    rating: 4.2,
  },
  {
    id: 11,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
    isPremium: false,
    isFavorite: false,
    price: 190,
    title: `The house among olive `,
    guests: 6,
    bedrooms: 5,
    description: `I am happy to welcome you to my apartment in the city center! Three words: location, cosy and chic!`,
    facilities: [`Washer`, `Breakfast`, `Laptop friendly workspace`],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [53.534341000000005, 9.998654],
    locationZoom: 16,
    cityName: `Hamburg`,
    cityCoordinates: [53.550341, 10.000654],
    cityZoom: 13,
    type: `house`,
    rating: 4.3,
  },
  {
    id: 12,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
    isPremium: true,
    isFavorite: false,
    price: 154,
    title: `The house among olive `,
    guests: 7,
    bedrooms: 3,
    description: `I am happy to welcome you to my apartment in the city center! Three words: location, cosy and chic!`,
    facilities: [
      `Washer`,
      `Laptop friendly workspace`,
      `Baby seat`,
      `Air conditioning`,
      `Breakfast`,
      `Towels`,
    ],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [51.225402, 6.784314],
    locationZoom: 16,
    cityName: `Dusseldorf`,
    cityCoordinates: [51.225402, 6.776314],
    cityZoom: 13,
    type: `apartment`,
    rating: 3.9,
  },
];

export const favoriteOffers = [
  {
    id: 10,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
    isPremium: false,
    isFavorite: true,
    price: 125,
    title: `Penthouse, 4-5 rooms + 5 balconies`,
    guests: 2,
    bedrooms: 1,
    description: `Design interior in most sympathetic area! Complitely renovated, well-equipped, cosy studio in idyllic,
    over 100 years old wooden house. Calm street, fast connection to center and airport.`,
    facilities: [
      `Breakfast`,
      `Laptop friendly workspace`,
      `Air conditioning`,
      `Washer`,
    ],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [51.211402, 6.756314000000001],
    locationZoom: 16,
    cityName: `Dusseldorf`,
    cityCoordinates: [51.225402, 6.776314],
    cityZoom: 13,
    type: `apartment`,
    rating: 4.2,
  },
  {
    id: 11,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
    isPremium: false,
    isFavorite: true,
    price: 190,
    title: `The house among olive `,
    guests: 6,
    bedrooms: 5,
    description: `I am happy to welcome you to my apartment in the city center! Three words: location, cosy and chic!`,
    facilities: [`Washer`, `Breakfast`, `Laptop friendly workspace`],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [53.534341000000005, 9.998654],
    locationZoom: 16,
    cityName: `Hamburg`,
    cityCoordinates: [53.550341, 10.000654],
    cityZoom: 13,
    type: `house`,
    rating: 4.3,
  },
  {
    id: 12,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
    isPremium: true,
    isFavorite: true,
    price: 154,
    title: `The house among olive `,
    guests: 7,
    bedrooms: 3,
    description: `I am happy to welcome you to my apartment in the city center! Three words: location, cosy and chic!`,
    facilities: [
      `Washer`,
      `Laptop friendly workspace`,
      `Baby seat`,
      `Air conditioning`,
      `Breakfast`,
      `Towels`,
    ],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [51.225402, 6.784314],
    locationZoom: 16,
    cityName: `Dusseldorf`,
    cityCoordinates: [51.225402, 6.776314],
    cityZoom: 13,
    type: `apartment`,
    rating: 3.9,
  },
  {
    id: 1,
    previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
    isPremium: false,
    isFavorite: true,
    price: 493,
    title: `The house among olive `,
    guests: 4,
    bedrooms: 3,
    description: `Discover daily local life in city center, friendly neighborhood, clandestine casino,
    karaoke, old-style artisans, art gallery and artist studio downstairs.`,
    facilities: [
      `Laptop friendly workspace`,
      `Washer`,
      `Towels`,
      `Fridge`,
      `Air conditioning`,
      `Baby seat`,
      `Breakfast`,
    ],
    images: [
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
      `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
    ],
    host: {
      id: 25,
      isPro: true,
      name: `Angelina`,
      avatar: `img/avatar-angelina.jpg`,
    },
    locationCoordinates: [50.957361, 6.9509739999999995],
    locationZoom: 16,
    cityName: `Cologne`,
    cityCoordinates: [50.938361, 6.959974],
    cityZoom: 13,
    type: `house`,
    rating: 3.8,
  },
];

export const sortedFavoriteOffers = {
  Cologne: [
    {
      id: 1,
      previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
      isPremium: false,
      isFavorite: true,
      price: 493,
      title: `The house among olive `,
      guests: 4,
      bedrooms: 3,
      description: `Discover daily local life in city center, friendly neighborhood, clandestine casino,
      karaoke, old-style artisans, art gallery and artist studio downstairs.`,
      facilities: [
        `Laptop friendly workspace`,
        `Washer`,
        `Towels`,
        `Fridge`,
        `Air conditioning`,
        `Baby seat`,
        `Breakfast`,
      ],
      images: [
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
      ],
      host: {
        id: 25,
        isPro: true,
        name: `Angelina`,
        avatar: `img/avatar-angelina.jpg`,
      },
      locationCoordinates: [50.957361, 6.9509739999999995],
      locationZoom: 16,
      cityName: `Cologne`,
      cityCoordinates: [50.938361, 6.959974],
      cityZoom: 13,
      type: `house`,
      rating: 3.8,
    },
  ],

  Dusseldorf: [
    {
      id: 10,
      previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
      isPremium: false,
      isFavorite: true,
      price: 125,
      title: `Penthouse, 4-5 rooms + 5 balconies`,
      guests: 2,
      bedrooms: 1,
      description: `Design interior in most sympathetic area! Complitely renovated, well-equipped, cosy studio in idyllic,
    over 100 years old wooden house. Calm street, fast connection to center and airport.`,
      facilities: [
        `Breakfast`,
        `Laptop friendly workspace`,
        `Air conditioning`,
        `Washer`,
      ],
      images: [
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
      ],
      host: {
        id: 25,
        isPro: true,
        name: `Angelina`,
        avatar: `img/avatar-angelina.jpg`,
      },
      locationCoordinates: [51.211402, 6.756314000000001],
      locationZoom: 16,
      cityName: `Dusseldorf`,
      cityCoordinates: [51.225402, 6.776314],
      cityZoom: 13,
      type: `apartment`,
      rating: 4.2,
    },
    {
      id: 12,
      previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
      isPremium: true,
      isFavorite: true,
      price: 154,
      title: `The house among olive `,
      guests: 7,
      bedrooms: 3,
      description: `I am happy to welcome you to my apartment in the city center! Three words: location, cosy and chic!`,
      facilities: [
        `Washer`,
        `Laptop friendly workspace`,
        `Baby seat`,
        `Air conditioning`,
        `Breakfast`,
        `Towels`,
      ],
      images: [
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
      ],
      host: {
        id: 25,
        isPro: true,
        name: `Angelina`,
        avatar: `img/avatar-angelina.jpg`,
      },
      locationCoordinates: [51.225402, 6.784314],
      locationZoom: 16,
      cityName: `Dusseldorf`,
      cityCoordinates: [51.225402, 6.776314],
      cityZoom: 13,
      type: `apartment`,
      rating: 3.9,
    },
  ],
  Hamburg: [
    {
      id: 11,
      previewImage: `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
      isPremium: false,
      isFavorite: true,
      price: 190,
      title: `The house among olive `,
      guests: 6,
      bedrooms: 5,
      description: `I am happy to welcome you to my apartment in the city center! Three words: location, cosy and chic!`,
      facilities: [`Washer`, `Breakfast`, `Laptop friendly workspace`],
      images: [
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
        `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`,
      ],
      host: {
        id: 25,
        isPro: true,
        name: `Angelina`,
        avatar: `img/avatar-angelina.jpg`,
      },
      locationCoordinates: [53.534341000000005, 9.998654],
      locationZoom: 16,
      cityName: `Hamburg`,
      cityCoordinates: [53.550341, 10.000654],
      cityZoom: 13,
      type: `house`,
      rating: 4.3,
    },
  ],
};
