import React from "react";
import renderer from "react-test-renderer";
import App from "./app";

const offers = [
  {
    bedrooms: 3,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Amsterdam`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.`,
    goods: [
      `Heating`,
      `Kitchen`,
      `Cable TV`,
      `Washing machine`,
      `Coffee machine`,
      `Dishwasher`,
    ],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 1,
      is_pro: true,
      name: `Angelina`,
    },
    id: 1,
    images: [`/img/apartment-01.jpg`, `/img/apartment-02.jpg`],
    is_favorite: false,
    is_premium: false,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-01.jpg`,
    price: 120,
    rating: 4.8,
    title: `Beautiful & luxurious studio at great location`,
    type: `apartment`,
  },

  {
    bedrooms: 2,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Amsterdam`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.`,
    goods: [
      `Heating`,
      `Kitchen`,
      `Cable TV`,
      `Washing machine`,
      `Coffee machine`,
      `Dishwasher`,
    ],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 11,
      is_pro: true,
      name: `Angelina`,
    },
    id: 11,
    images: [`/img/apartment-03.jpg`, `/img/apartment-02.jpg`],
    is_favorite: false,
    is_premium: false,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-03.jpg`,
    price: 150,
    rating: 4.7,
    title: `Beautiful & luxurious studio at great location`,
    type: `apartment`,
  },
  {
    bedrooms: 2,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Amsterdam`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness ..s.`,
    goods: [
      `Heating`,
      `Kitchen`,
      `Cable TV`,
      `Washing machine`,
      `Coffee machine`,
      `Dishwasher`,
    ],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 2,
      is_pro: true,
      name: `Angel`,
    },
    id: 2,
    images: [`/img/apartment-03.jpg`, `/img/apartment-02.jpg`],
    is_favorite: false,
    is_premium: false,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-03.jpg`,
    price: 150,
    rating: 4.7,
    title: `Beautiful & luxurious studio at great location`,
    type: `apartment`,
  },

  {
    bedrooms: 2,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Paris`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness...`,
    goods: [
      `Heating`,
      `Kitchen`,
      `Cable TV`,
      `Washing machine`,
      `Coffee machine`,
      `Dishwasher`,
    ],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 3,
      is_pro: true,
      name: `Ksyusha`,
    },
    id: 3,
    images: [`/img/apartment-01.jpg`, `/img/apartment-02.jpg`],
    is_favorite: false,
    is_premium: false,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-01.jpg`,
    price: 100,
    rating: 4.9,
    title: `Beautiful & luxurious studio at great location`,
    type: `apartment`,
  },

  {
    bedrooms: 2,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Paris`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness...`,
    goods: [`Heating`, `Kitchen`, `Cable TV`, `Washing machine`],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 4,
      is_pro: true,
      name: `Katya`,
    },
    id: 4,
    images: [`/img/apartment-03.jpg`, `/img/apartment-02.jpg`],
    is_favorite: false,
    is_premium: false,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-03s.jpg`,
    price: 140,
    rating: 4.3,
    title: `Beautiful & luxurious studio at great location`,
    type: `apartment`,
  },

  {
    bedrooms: 2,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Cologne`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness...`,
    goods: [
      `Heating`,
      `Kitchen`,
      `Cable TV`,
      `Washing machine`,
      `Coffee machine`,
      `Dishwasher`,
    ],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 5,
      is_pro: true,
      name: `Amy`,
    },
    id: 5,
    images: [`/img/apartment-01.jpg`, `/img/apartment-02.jpg`],
    is_favorite: false,
    is_premium: false,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-01.jpg`,
    price: 150,
    rating: 4.4,
    title: `Beautiful & luxurious studio at great location`,
    type: `room`,
  },
  {
    bedrooms: 1,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Cologne`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness...`,
    goods: [`Heating`, `Kitchen`, `Cable TV`, `Washing machine`],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 6,
      is_pro: true,
      name: `Amily`,
    },
    id: 6,
    images: [`/img/apartment-03.jpg`, `/img/apartment-02.jpg`],
    is_favorite: false,
    is_premium: false,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-03.jpg`,
    price: 100,
    rating: 4.3,
    title: `Beautiful & luxurious studio at great location`,
    type: `room`,
  },

  {
    bedrooms: 3,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Brussels`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness...`,
    goods: [
      `Heating`,
      `Kitchen`,
      `Cable TV`,
      `Washing machine`,
      `Coffee machine`,
      `Dishwasher`,
    ],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 7,
      is_pro: true,
      name: `Alex`,
    },
    id: 7,
    images: [`/img/apartment-01.jpg`, `/img/apartment-02.jpg`],
    is_favorite: false,
    is_premium: false,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-01.jpg`,
    price: 170,
    rating: 4.7,
    title: `Beautiful & luxurious studio at great location`,
    type: `room`,
  },
  {
    bedrooms: 3,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Brussels`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness...`,
    goods: [
      `Heating`,
      `Kitchen`,
      `Cable TV`,
      `Washing machine`,
      `Coffee machine`,
      `Dishwasher`,
    ],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 8,
      is_pro: true,
      name: `Iren`,
    },
    id: 8,
    images: [`/img/apartment-03.jpg`, `/img/apartment-02.jpg`],
    is_favorite: false,
    is_premium: false,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-03.jpg`,
    price: 150,
    rating: 4.6,
    title: `Beautiful & luxurious studio at great location`,
    type: `room`,
  },
  {
    bedrooms: 3,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Hamburg`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness...`,
    goods: [
      `Heating`,
      `Kitchen`,
      `Cable TV`,
      `Washing machine`,
      `Coffee machine`,
      `Dishwasher`,
    ],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 9,
      is_pro: true,
      name: `Amelia`,
    },
    id: 9,
    images: [`/img/apartment-03.jpg`, `/img/apartment-02.jpg`],
    is_favorite: false,
    is_premium: false,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-03.jpg`,
    price: 120,
    rating: 4.9,
    title: `Beautiful & luxurious studio at great location`,
    type: `room`,
  },
  {
    bedrooms: 3,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Hamburg`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness...`,
    goods: [
      `Heating`,
      `Kitchen`,
      `Cable TV`,
      `Washing machine`,
      `Coffee machine`,
      `Dishwasher`,
    ],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 10,
      is_pro: true,
      name: `Alex`,
    },
    id: 10,
    images: [`/img/apartment-01.jpg`, `/img/apartment-02.jpg`],
    is_favorite: false,
    is_premium: false,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-01.jpg`,
    price: 190,
    rating: 4.5,
    title: `Beautiful & luxurious studio at great location`,
    type: `room`,
  },
  {
    bedrooms: 3,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Dusseldorf`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness...`,
    goods: [
      `Heating`,
      `Kitchen`,
      `Cable TV`,
      `Washing machine`,
      `Coffee machine`,
      `Dishwasher`,
    ],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 10,
      is_pro: true,
      name: `Alex`,
    },
    id: 10,
    images: [`/img/apartment-01.jpg`, `/img/apartment-02.jpg`],
    is_favorite: false,
    is_premium: false,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-01.jpg`,
    price: 160,
    rating: 4.2,
    title: `Beautiful & luxurious studio at great location`,
    type: `room`,
  },

  {
    bedrooms: 3,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Hamburg`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness...`,
    goods: [
      `Heating`,
      `Kitchen`,
      `Cable TV`,
      `Washing machine`,
      `Coffee machine`,
      `Dishwasher`,
    ],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 12,
      is_pro: true,
      name: `Alex`,
    },
    id: 12,
    images: [`/img/apartment-01.jpg`, `/img/apartment-02.jpg`],
    is_favorite: false,
    is_premium: false,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-01.jpg`,
    price: 190,
    rating: 4.5,
    title: `Beautiful & luxurious studio at great location`,
    type: `room`,
  },
  {
    bedrooms: 3,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Dusseldorf`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness...`,
    goods: [
      `Heating`,
      `Kitchen`,
      `Cable TV`,
      `Washing machine`,
      `Coffee machine`,
      `Dishwasher`,
    ],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 13,
      is_pro: true,
      name: `Alina`,
    },
    id: 13,
    images: [`/img/apartment-03.jpg`, `/img/apartment-02.jpg`],
    is_favorite: false,
    is_premium: true,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-03.jpg`,
    price: 190,
    rating: 4.9,
    title: `Beautiful & luxurious studio at great location`,
    type: `room`,
  },
];

const favoriteOffers = [
  {
    bedrooms: 3,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Hamburg`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness...`,
    goods: [
      `Heating`,
      `Kitchen`,
      `Cable TV`,
      `Washing machine`,
      `Coffee machine`,
      `Dishwasher`,
    ],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 12,
      is_pro: true,
      name: `Alex`,
    },
    id: 12,
    images: [`/img/apartment-01.jpg`, `/img/apartment-02.jpg`],
    is_favorite: true,
    is_premium: false,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-01.jpg`,
    price: 190,
    rating: 4.5,
    title: `Beautiful & luxurious studio at great location`,
    type: `room`,
  },
  {
    bedrooms: 3,
    city: {
      location: {
        latitude: 52.370216,
        longitude: 4.895168,
        zoom: 10,
      },
      name: `Dusseldorf`,
    },
    description:
      `A quiet cozy and picturesque that hides behind a a river by the unique lightness...`,
    goods: [
      `Heating`,
      `Kitchen`,
      `Cable TV`,
      `Washing machine`,
      `Coffee machine`,
      `Dishwasher`,
    ],
    host: {
      avatar_url: `/img/avatar-angelina.jpg`,
      id: 13,
      is_pro: true,
      name: `Alina`,
    },
    id: 13,
    images: [`/img/apartment-03.jpg`, `/img/apartment-02.jpg`],
    is_favorite: true,
    is_premium: true,
    location: {
      latitude: 52.35514938496378,
      longitude: 4.673877537499948,
      zoom: 8,
    },
    max_adults: 4,
    preview_image: `/img/apartment-03.jpg`,
    price: 190,
    rating: 4.9,
    title: `Beautiful & luxurious studio at great location`,
    type: `room`,
  },
];

describe(`<App /> render`, () => {
  it(`renders correctly with full of descriptionrmation`, () => {
    const tree = renderer
      .create(<App offersAll={offers} favoriteOffers={favoriteOffers} />)
      .toJSON();

    expect(tree).toMatchSnapshot();
  });
});
